# Generated by Django 2.1.5 on 2020-01-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200121_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
